### PR TITLE
Fix fatal error for array_map() in sanitization check

### LINKED ISSUE #372: Unsupported operand types
~~~
PHP Fatal error:  Unsupported operand types in .../WordPress/Sniff.php on line 436
~~~

Happened with PHP 5.4.38 and 5.6.8, when running PHPCS with WPCS on develop branch of [TGMPA](https://github.com/thomasgriffin/tgm-plugin-activation).

Call Stack:
1. {main}() .../phpcs/scripts/phpcs:0
2. PHP_CodeSniffer_CLI->runphpcs() .../phpcs/scripts/phpcs:25
3. PHP_CodeSniffer_CLI->process() .../phpcs/CodeSniffer/CLI.php:95
4. PHP_CodeSniffer->processFiles() .../phpcs/CodeSniffer/CLI.php:867
5. PHP_CodeSniffer->processFile() .../phpcs/CodeSniffer.php:619
6. PHP_CodeSniffer->_processFile() .../phpcs/CodeSniffer.php:1679
7. PHP_CodeSniffer_File->start() .../phpcs/CodeSniffer.php:1801
8. WordPress_Sniffs_CSRF_NonceVerificationSniff->process() .../phpcs/CodeSniffer/File.php:567
9. WordPress_Sniff->is_only_sanitized() .../wpcs/WordPress/Sniffs/CSRF/NonceVerificationSniff.php:119
10. WordPress_Sniff->is_sanitized() .../wpcs/WordPress/Sniff.php:343

### PR DESCRIPTION
**Pull request by JDGrimes**
We might want to consider doing a 0.4.1 release with this fix included.

Fixes #372

### CODE REVIEW

**Comment by GaryJones** [comment]
What was it about TGMPA that triggered the error in the first place?

**Comment by GaryJones** [comment]
PR fixes the error for me, thanks.

I've got no objections for 0.4.1 going out with this. Now we've got a monthly release schedule for new features, having bug fixes go out as patch releases makes sense - we don't have to store them up for any longer than need be; get them out to users. cc @westonruter.

**Comment by JDGrimes** [comment]
> What was it about TGMPA that triggered the error in the first place?

It was that `$function_opener`, which was actually an integer, was being treated like an array too. I didn't realize my mistake because there were no tests that triggered this part of the code (I'll be adding some soon).

**Comment by JDGrimes** [comment]
> I've got no objections for 0.4.1 going out with this.

I just realized that this change didn't go out in 0.4.0 anyway, since it was actually part of the CSRF sniff PR. So no need for a 0.4.1.

**Comment by GaryJones** [comment]
> It was that $function_opener, which was actually an integer,

But which bit of TGMPA triggered this, which other files of code didnt?

**Comment by JDGrimes** [comment]
Somewhere that was using a user input variable and (probably) sanitizing it with `array_map()` (and so was being checked by the CSRF sniff).

**Pull request merged**
