### PR TITLE
Release version 2.0.0

### LINKED ISSUE #1389: Timing of version 2.0.0
I [previously proposed to drop PHPCS 2.x support and remove all deprecated sniffs by end of August](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1048) - largely with an eye on being able to have a different namespace to prevent clashes with the WP project itself.

I'd like to propose changing that deadline to end of December 2018 for the following reasons:
1. WPCS 1.0.0 deprecates a number of sniffs which we'd want to remove in v 2.0.0.
2. WPCS 1.0.0 contains breaking changes, most notably the re-categorization of a number of sniffs.
3. At this moment, it doesn't look like WP Core will drop PHP 5.2/start using namespaces within the next six months, so the namespace reason is less urgent.

As there are numerous standards out there which have WPCS as a dependency, we ought to allow them some time to adjust their standard. and two (summer/vacation) months does not really sound long enough, which is why I'm proposing moving the 2.0.0 release back to the end of the year.

Opinions ?

/cc @WordPress-Coding-Standards/wpcs-admins

### PR DESCRIPTION
**Pull request by jrfnl**
:warning: **DO NOT MERGE (YET)** :warning: 

PR for tracking changes for the 2.0.0 release. Target release date: **Wednesday January 16**.
- [x] Add changelog for 2.0.0 - PR #1625
- [ ] Merge this PR
- [ ] Add release tag & copy & paste the changelog to it
- [ ] Close the 2.0.0 milestone
- [x] Open a new milestone for the next release
- [x] If any open PRs which were milestoned for 2.0.0 do not make it into the release, update their milestone.
- [ ] Tweet about the release.
- [ ] Post about it in Slack.
- [ ] Submit for "Month in WordPress": https://make.wordpress.org/community/month-in-wordpress-submissions/
- [ ] Open PR to merge `master` into `develop` to get rid of the _This branch is out-of-date with the base branch_ messages on each release.

Closes #1389

### CODE REVIEW

**Comment by jrfnl** [comment]
Are we ready for doing this ?

**Comment by GaryJones** [comment]
@jrfnl Go for it!

**Comment by ashish200025** [comment]
great

**Comment by jrfnl** [comment]
Release tweet: https://twitter.com/jrf_nl/status/1085482419682246656

**Pull request merged**
