### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ramonamorea**
Added the guide to set up WPCS when using Eclipse with XAMPP.

### CODE REVIEW

**Comment by JDGrimes** [comment]
The [Travis failure](https://travis-ci.org/WordPress-Coding-Standards/WordPress-Coding-Standards/jobs/313142388#L707-L759) appears to me to be a bug in PHPCS, and not any issue with WPCS or this PR. In that case, I suppose it should be reported upstream.

**Comment by jrfnl** [comment]
Correct, the Travis error is unrelated. I've identified which upstream commit is causing it & have reported it there: https://github.com/squizlabs/PHP_CodeSniffer/commit/21315b25d9ecfd9adc07d7c2c552527f5578e586#r26132171

**Comment by jrfnl** [comment]
The above mentioned issue should be fixed now. I've just restarted the job in Travis. Fingers crossed that the build now passes :crossed_fingers:

**Comment by jrfnl** [comment]
Thank you @ramonamorea !

As a side-note for anyone who has some time to spare: the list with IDE specific instructions in the readme is pretty long by now, so maybe it's a good idea to move some more of these to separate wiki pages with just a reference to the wiki in the Readme.... ?

**Comment by dingo-d** [comment]
I think a link to wiki page is a good solution.

**Pull request merged**
