### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by jrfnl**
PR for tracking changes for 0.11.0. 
- [x] Add changelog for 0.11.0
- [ ] Merge PR
- [ ] Add release tag

Closes #861

### CODE REVIEW

**Comment by jrfnl** [comment]
@WordPress-Coding-Standards/wpcs-admins Just checking: anyone working on the changelog yet ?

**Comment by JDGrimes** [comment]
Sorry, no. I have to admit that I'm busy enough that I probably shouldn't try to tackle it at the moment.

If the whole thing seems too daunting, maybe several different folks can split it up and tackle different sets of changes (e.g., one can take the first part and somebody else the second, or something like that).

I know @jrfnl has really outdone himself again with this release (🎉⚡️🔥). I guess to some degree the person who created a lot of the changes can probably more quickly create the changelog for them, but it also isn't fair that @jrfnl should have to do this on top of all his other great contributions if he doesn't have the time the right now. @jrfnl — Are you asking because you were planning to do it or because you aren't really planning to do it?

**Comment by jrfnl** [comment]
@JDGrimes Eh.. you may want to change the gender connotations in your message ;-)

> Are you asking because you were planning to do it or because you aren't really planning to do it?

I was asking as I was thinking of making a start but don't want to waste time if someone else is already working on it. Got plenty to do without doing this too ;-)

If nobody else is already working on it, I'll try and make a start & push each commit, that way if someone else has the time, they can contribute to the WIP branch, we can always squash the commits later. Does that sound like a plan ?

**Comment by GaryJones** [comment]
Sorry, I've not done any, and with WCLDN and trying to sell the house, I'm not going to be able to do anything any time soon.

**Comment by JDGrimes** [comment]
> @JDGrimes Eh.. you may want to change the gender connotations in your message ;-)

Oops. Yeah, sorry! :-)



> If nobody else is already working on it, I'll try and make a start & push each commit, that way if someone else has the time, they can contribute to the WIP branch, we can always squash the commits later. Does that sound like a plan ?

Definitely sounds like a plan to me. If I do get a chance, I'll jump in.

**Comment by jrfnl** [comment]
@JDGrimes Thanks :heart_eyes:

**Comment by jrfnl** [comment]
@GaryJones How was WC London ? Would you like to say 'yeah' to the release or shall go ahead and release it now ?

**Pull request merged**
