### PR TITLE
Add dev-lib and use for dogfooding rulesets (WordPress-Core) in Travis CI builds

### LINKED ISSUE #256: Settle on coding convention for WPCS snfifs
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/a446a38416b563393a248562a3c204b5c60ecfe5#commitcomment-8129539.

> But in reality this is the least of the problems in the coding style of the WPCS sniffs. It's currently a mismash of the conventions outlined in the PHPCS coding standards and the WPCS coding standards. There needs to be a comprehensive sweep done to fix them up (after all PRs are merged).

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #256.

### CODE REVIEW

**Comment by JDGrimes** [comment]
This appears to be failing on HHVM: https://travis-ci.org/WordPress-Coding-Standards/WordPress-Coding-Standards/jobs/143952804

`develop` doesn't currently fail on HHVM, so that would be a regression.

**Comment by westonruter** [comment]
Humm. It seems to be failing during the install step but it doesn't indicate what the failure is. I'm not sure actually if dev-lib has run on the HHVM environment yet.

**Comment by GaryJones** [comment]
Can you please summarise what this change is doing?

**Comment by westonruter** [comment]
It's just using wp-dev-lib's builtin PHP syntax check and PHPCS running. The key feature of wp-dev-lib here is the ability to restrict error reporting to the changes in a PR. However, with #590 it is not necessary since the whole codebase is now getting cleaned.

**Comment by ntwb** [comment]
> `develop` doesn't currently fail on HHVM, so that would be a regression.

Things might be different after #595 which updates the HHVM job to use the latest HHVM

**Comment by JDGrimes** [comment]
@westonruter Feel free to open another PR if you want to still use the dev-lib for syntax checking, etc.

**Pull request closed without merging**
