### PR TITLE
Remove repo specific CoC file.

### PR DESCRIPTION
**Pull request by desrosj**
This removes the repository specific `CODE_OF_CONDUCT.md` file in favor of the newly added version maintained as the organization's default within the WordPress/.github repository.

While this file will not be included in `git clone`s, it will be displayed on the repository's main page and anywhere else GitHub includes a Code of Conduct link.

This change enables more consistent messaging for the community code of conduct, which is adapted from the same Contributor Covenant currently used for the CoC file being removed. It also allows the file to be updated in one location for all repositories under the WordPress organization.

See https://github.com/WordPress/.github/pull/1.

### CODE REVIEW

**Comment by jrfnl** [comment]
@desrosj In principle agreed, but the file as per https://github.com/WordPress/.github/pull/1 is a very abbreviated version of the CoC, which I don't think conveys the right message.

Either that file should include the complete CoC as per https://make.wordpress.org/handbook/community-code-of-conduct/ or it should just be a simple paragraph pointing to the handbook page containing the CoC.

Anything in between will lead to confusion and can cause problems with enforcement.

I also wonder if the CoC should include some empowerment for repo managers/maintainers regarding behaviour in a specific repo ? At times swift action can be needed and while a diligent investigation via the IRT is always a good thing, harm can be experienced in the mean time when such a process is long and time-consuming.

**Comment by desrosj** [comment]
Thanks @jrfnl! 

The goal with https://github.com/WordPress/.github/pull/1 was to create a brief file and link out to the full CoC page in the handbook, which it does after the first paragraph.

I'm going to defer these questions to @angelasjin, though. While I worked with her on the abbreviated file and I'm helping her by creating these PRs to show the default file in all the organization's repositories, those are things that she'll need to weigh in on.

**Comment by angelasjin** [comment]
Hello! Thanks for sharing your thoughts, @jrfnl, and for tagging me in, @desrosj. 

The CoC does include an [Enforcement Responsibilities section](https://make.wordpress.org/handbook/community-code-of-conduct/#enforcement-responsibilities), which states the following: 

```
Community leaders (such as team reps, component maintainers, organizers, and project leads)  are responsible for clarifying and enforcing our standards of acceptable behavior; they will take appropriate and fair corrective action in response to any behavior that they deem inappropriate, threatening, offensive, or harmful.

Community leaders have the right and responsibility to remove, edit, or reject comments, commits, code, documentation edits, issues, videos, presentations, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate.
```

Does this cover what you were hoping to see? If you would like to see edits, I recommend that we make them to the version in the Contributor Handbook as that is our primary source. To suggest edits, you can email support@wordcamp.org.

**Comment by angelasjin** [comment]
Hey @jrfnl! It sounds like I might have misunderstood your concern then. Let me double check my understanding before I try to give you another response? 

It seemed like you were looking for repo managers/maintainers to be able to take some faster actions when you see inappropriate behaviors in repos, and hoped to see the CoC include language to that effect, is that correct? Are the additional concerns?

**Comment by jrfnl** [comment]
> Hey @jrfnl! It sounds like I might have misunderstood your concern then. Let me double check my understanding before I try to give you another response?
> 
> It seemed like you were looking for repo managers/maintainers to be able to take some faster actions when you see inappropriate behaviors in repos, and hoped to see the CoC include language to that effect, is that correct? Are the additional concerns?

See: https://github.com/WordPress/WordPress-Coding-Standards/pull/2423#issuecomment-1947647225

**Comment by angelasjin** [comment]
Are you referring to the part about the CoC being abbreviated? As Jon noted, and I agree, the goal was to create a brief file and link to the full CoC page in the handbook, which it does twice. I personally feel like this works and sends the right message, but perhaps we disagree.

**Comment by jrfnl** [comment]
@GaryJones @dingo-d Shall we close this PR ? I don't think an abbreviated CoC with a reference to someone's personal site for the full version is a good idea.

**Comment by GaryJones** [comment]
Yes, let's close it for now.

**Pull request closed without merging**
