### PR TITLE
Apply snakeCase naming whitelist to vars

### PR DESCRIPTION
**Pull request by JDGrimes**
Not just properties as former logic did (inadvertently, I think).

### CODE REVIEW

**Comment by JDGrimes** [comment]
OK, it looks like the tests were checking for the old behavior, so the build is failing. I wonder whether we should allow the properties and variables to be whitelisted separately? We could even use a single list, but prefix the variables with `$`. Thoughts?

**Comment by jrfnl** [comment]
Related #551 #549 

My two pennies:

With object properties you may not always have a choice which case to use as you can extend native PHP classes or classes from other sources which will force you to use the code style of the parent class, so whitelisting makes sense.

For variables, you (should) always have a choice and these therefore should comply with the WP coding standards without exception (ok, with the exception of native PHP variables which do not comply, but those are whitelisted anyway)

**Comment by JDGrimes** [comment]
Yeah, after thinking over this more, I guess maybe it is better not to allow whitelisting of variables. My reason for expecting it was that the name of the whitelist is `customVariablesWhitelist`. Shouldn't that be changed to `customPropertiesWhitelist` instead? (although that would break back-compat, unless we just deprecate `customVariablesWhitelist` for now). The reason that I wanted to use it was that I have some Codeception tests for a plugin, and these heavily use `$I` to hold the user object. However, I can just exclude this sniff from running over that directory. The other variable that I wanted to whitelist was `$EZSQL_ERROR`. It is an ancient remnant of the merge of ezsql into core as `wpdb`, and I use it in my PHPUnit tests to catch database errors. We can add that to the built-in variable whitelist, or else I'll just exclude those files for this sniff in my ruleset as well.

**Comment by jrfnl** [comment]
> Shouldn't that be changed to customPropertiesWhitelist instead? (although that would break back-compat, unless we just deprecate customVariablesWhitelist for now).

*grin* I'd had that same _"hang on !?"_ moment a while back and decided against sending in a PR to avoid breaking backward compatibility, but a PR for it does make sense as the property name is currently confusing.


> The other variable that I wanted to whitelist was $EZSQL_ERROR. It is an ancient remnant of the merge of ezsql into core as wpdb

If `$EZSQL_ERROR` is part of WP - even though rarely used in userland - whitelisting it makes sense to me.

**Comment by jrfnl** [comment]
Just thinking: we could even be stricter/more precise with the property name check and only allow deviations when the class extends another class or interface (or if the property is whitelisted).

**Comment by jrfnl** [comment]
@JDGrimes Just doing some clean up. Can I delete this branch ?

**Comment by JDGrimes** [comment]
> @JDGrimes Just doing some clean up. Can I delete this branch ?

@jrfnl done.

**Pull request closed without merging**
