### PR TITLE
Strict Comparisons Sniff and Unit Tests

### PR DESCRIPTION
**Pull request by mattyrob**
Linked to:
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/242

### CODE REVIEW

**Comment by GaryJones** [comment]
Did this get merged under a different PR?

**Comment by mattyrob** [comment]
I'm not sure, I had issues with my repository though and had to delete it and start again, so maybe that closed this ticket. I'll try to recreate it with my new repository when I get a few minutes.

**Comment by GaryJones** [comment]
Appreciated, thanks @mattyrob.

**Comment by mattyrob** [comment]
See #351

**Pull request closed without merging**
