### PR TITLE
FileNames: add template exceptions, class and template tags rules

### LINKED ISSUE #470: WordPress.Files.FileName.UnderscoresNotAllowed and the template hierarchy
Currently, this standard will throw an error if a file is encountered whose filename contains an underscore:

```
 1 | ERROR | [ ] Filename "taxonomy-post_format-post-format-link.php"
   |       |     with underscores found; use
   |       |     taxonomy-post-format-post-format-link.php instead
   |       |     (WordPress.Files.FileName.UnderscoresNotAllowed)
```

Technically, this is correct. The [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/) states that "hyphens should separate words" in file names. However, this may conflict with the [template hierarchy's requirements](https://developer.wordpress.org/themes/basics/template-hierarchy/), which use post types and taxonomies (as well as page/post slugs, author nicenames, mime types, and more) as part of the file name. For instance, from the docs on the template hierarchy,

> In the case of post formats, the taxonomy is ‘post_format’ and the terms are ‘post-format-{format}. i.e. taxonomy-post_format-post-format-link.php for the link post format.

Therefore, the file _unavoidably_ named `taxonomy-post_format-post-format-link.php` will throw an error as in the example above. I understand that exclusions can be added to the ruleset, but I think the question should still be raised: **Should template hierarchy files be excepted from this sniff?**

### LINKED ISSUE #642: Add additional file name checks
> Class file names should be based on the class name with class- prepended and the underscores in the class name replaced with hyphens, for example WP_Error becomes:
> 
> `class-wp-error.php`
> 
> This file-naming standard is for all current and new files with classes. There is one exception for three files that contain code that got ported into BackPress: class.wp-dependencies.php, class.wp-scripts.php, class.wp-styles.php. Those files are prepended with class., a dot after the word class instead of a hyphen.
> 
> Files containing template tags in wp-includes should have -template appended to the end of the name so that they are obvious.
> 
> `general-template.php`

Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions

This rule is currently not covered and would have been untestable, however, a recent change in PHPCS which will be included in PHPCS 2.7 will allow for this: https://github.com/squizlabs/PHP_CodeSniffer/issues/1078

### LINKED ISSUE #805: FileNameSniff triggers on taxonomy-{taxonomy_slug}.php files with underscores
The advice when registering a [custom taxonomy](https://codex.wordpress.org/Function_Reference/register_taxonomy) is "Name should only contain lowercase letters and the underscore character", yet if you do this and have a custom taxonomy with underscores such as `resource_category` then have a theme template called `taxonomy-resource_category` the FileNameSniff triggers.

According to the [template hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/#custom-taxonomies) documentation this sniff would also trigger if a theme were to customise based on post formats, such as `taxonomy-post_format.php`.

Seems to be that the sniff needs to take into account these taxonomy template files and allow these instances.

### PR DESCRIPTION
**Pull request by jrfnl**
This PR takes care of the - up to now - uncovered parts of the file name rules as outlined in #642.
It also adds a `public $is_theme` property, which when set to `true` via the ruleset will gracefully deal with exceptions to the file name rules for dynamic template file names as discussed in #470.

Notes:
* The `Core` ruleset used to include the `Generic.Files.LowercasedFilename` and this sniff for the file name checks. This would potentially lead to two messages being thrown with different suggestions about the expected file name. The lowercase check has now been incorporated into this sniff and the upstream sniff has been removed from the ruleset.
* The error message and the errorcode for this original check `UnderscoresNotAllowed` has changed to `NotHyphenatedLowercase` to better cover the check currently being executed.
* Added check for `class-` prefix for files containing a class including verification that the rest of the file name reflects the name of the class.
* Added check for `-template` suffix for files which are in the `wp-includes` directory and contain a `@subpackage Template` tag. This check will only be done for non-class files. This is in line with the current file names as used in WP Core.
* Added exception for dynamic template files. This requires that the custom ruleset sets the `is_theme` property to `true` (documentation upcoming in the wiki).
The exception covers nearly everything which is needed. The only uncovered part at this moment is "sublevel"-only mimetype template files, like `plain.php`.

Includes extensive unit tests for the sniff (was until now not unit tested)

Fixes #470
Fixes #642 
Fixes #805

### CODE REVIEW

**Comment by JDGrimes** [comment]
Nice work.

As a plugin developer that doesn't follow the (IMO, silly) naming convention for classes, I guess the only real difference for my plugin between this sniff and the `Generic.Files.LowercasedFilename`, will still just be that this sniff checks that hyphens are used in filenames instead of underscores (since the other checks won't run, and the class check will be disabled by my custom ruleset). In that case, I will probably exclude this sniff in my custom ruleset, for performance reasons, and use `Generic.Files.LowercasedFilename` instead. Because even if the errors from the class files are disabled in a custom ruleset, the check will still be run. There are ways that this could be mitigated, if you think that it is worth it, but personally I'll be just as happy with the generic sniff. I can foresee this being a fairly common circumstance though.

**Comment by jrfnl** [comment]
@JDGrimes I could easily add a public property to enable/disable the class and template tag rules completely (i.e. bow out before doing those checks) or disable them each individually (though the template one won't run if not in a directory with `/wp-includes/` in the path anyway).

Would that help ?

For a property name, I'm thinking `strict_class_file_names` and `strict_templatetag_file_names` with a boolean value. Or just `strict` if we'd make it an overall property.

**Comment by JDGrimes** [comment]
@jrfnl Yes, that would help. As you say, it is most important for the class filenames check, since the other only applies inside of the `wp-includes` directory. `strict_class_file_names` sounds good to me.

**Comment by jrfnl** [comment]
@JDGrimes Ok, done.

**Pull request merged**
