### PR TITLE
Null coalescing operator

### LINKED ISSUE #837: Null coalescing operator triggers `Detected usage of a non-validated input variable`
[Null coalescing operators](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op) were added to PHP in PHP7.  They are "syntactic sugar for the common case of needing to use a ternary in conjunction with isset(). It returns its first operand if it exists and is not NULL; otherwise it returns its second operand."

` $test = isset( $_GET['test'] ) ? $_GET['test'] : ''; ` 
can become 
`$test =  $_GET['test'] ?? '';`

At first glance, It looks like `WordPress_Sniff::is_in_isset_or_empty` needs to take Null coalescing operators into effect.

### PR DESCRIPTION
**Pull request by aaronjorbin**
Fixes #837

### CODE REVIEW

**Comment by jrfnl** [comment]
> Not sure how that will affect running against different PHP versions though.

As the code is tokenized, not parsed, it should be fine as long as the tokens are accounted for in the various PHP versions.

**Comment by jrfnl** [comment]
Summary of the outcome of my tests:
* Third test case breaks because of the brackets
* Fourth test case should give an error for unslash, but doesn't
* Testcase 5 to 7 give an error non validated error, but shouldn't
* Testcase 8 should give two errors, but gives none.

Here's the test code I've used:
```php
/*
 * Test recognition of the T_COALESCE token.
 */
$var = sanitize_text_field( wp_unslash( $_POST['foobar'] ?? '' ) ); // OK.
$var = sanitize_text_field( wp_unslash( $_POST['foobar']['sub'] ?? '' ) ); // OK.
$var = sanitize_text_field( wp_unslash( ( $_POST['foobar']['sub'] ) ?? '' ) ); // OK (extra brackets).
$var = sanitize_text_field( $_POST['foobar'] ?? '' ); // Bad x1 - unslash.

// The below two sets should give the same errors.
$var = $_POST['foobar'] ?? ''; // Bad x2 - sanitize + unslash.
$var = $_POST['foobar']['sub'] ?? ''; // Bad x2 - sanitize + unslash.
$var = ( $_POST['foobar']['sub'] ) ?? ''; // Bad x2 - sanitize + unslash.
$var = ( $_POST['foobar']['sub'] ?? '' ); // Bad x2 - sanitize + unslash.

$var = isset( $_POST['foobar'] ) ? $_POST['foobar'] : ''; // Bad x2 - sanitize + unslash.
$var = isset( $_POST['foobar']['sub'] ) ? $_POST['foobar']['sub'] : ''; // Bad x2 - sanitize + unslash.
$var = ( isset( $_POST['foobar']['sub'] ) ) ? $_POST['foobar']['sub'] : ''; // Bad x2 - sanitize + unslash.
$var = ( isset( $_POST['foobar']['sub'] ) ? $_POST['foobar']['sub'] : '' ); // Bad x2 - sanitize + unslash.
```

And these are the results:
```
----------------------------------------------------------------------
FOUND 20 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
  8 | ERROR | Detected usage of a non-validated input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotValidated)
  8 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
  8 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 12 | ERROR | Detected usage of a non-validated input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotValidated)
 12 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 12 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 13 | ERROR | Detected usage of a non-validated input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotValidated)
 13 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 13 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 14 | ERROR | Detected usage of a non-validated input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotValidated)
 14 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 14 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 17 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 17 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 18 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 18 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 19 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 19 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
 20 | ERROR | Missing wp_unslash() before sanitization.
    |       | (WordPress.VIP.ValidatedSanitizedInput.MissingUnslash)
 20 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST
    |       | (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)
----------------------------------------------------------------------
```

**Comment by jrfnl** [comment]
@aaronjorbin Hi Aaron, just checking in again to see if you are still interested in finishing this. If you haven't got time or lost interest, please let us know and we'll see if we can find someone to take over.

**Comment by aaronjorbin** [comment]
I'm not sure when I'll have time for this again, so if someone else is able to work on it they should absolutely feel free to.

**Comment by jrfnl** [comment]
@aaronjorbin Thanks for the quick reply. I'll see what I can do. WCEU contributors day coming up, so who knows ;-)

**Pull request closed without merging**
